### ISSUE TITLE
Real time indexing status for harvests

### ISSUE THREAD

**Issue by summer-cook** [harvard-lts/CURIOSity#109]
# Summary
From Maura & Phil in Slack:

> Our current spotlight gives us a real time indexing status, will that be happening here as well?

![Vanessa Venti's Personal Meeting Room - Zoom 2022-07-27 at 4 40 18 PM](https://user-images.githubusercontent.com/32469930/181390640-6bdd6a77-ad43-49b2-ac97-6d1e98327860.jpg)

**Comment by bkiahstroud** [comment]
We were not planning on adding that, no. That specific real time indexing status box is technically only intended to pop up when reindexing all items in an exhibit; the fact that it was showing up at all before was a byproduct of how harvesters handled indexing (which has since changed with the newer version of Spotlight). 

In the demo video that Vanessa sent us, she had said that the real time status was nice but not crucial, and that being able to see the status of the harvester somewhere was enough. In the newer version of Spotlight, that kind of information is on the Exhibit Dashboard within a modal: 

Demo of new behavior: https://share.getcloudapp.com/yAu1RndJ 

@VanessaVenti what are your thoughts? I know that you haven't had the chance to get hands-on experience with the new status tracking yet so no pressure, but if you do have thoughts at this point they would be helpful 🙂

**Comment by VanessaVenti** [comment]
@bkiahstroud - Yes, that's correct, having the realtime indexing status is on the items page is much less important than having a progress status on the dashboard page. So I think that's fine not to have that in 3.0, we just wanted to confirm we weren't supposed to be seeing it.

As for the modal window, I think that has the information I would need to know about the status of a job and any errors that come up. We did notice some usability issues though. The text doesn't wrap so we weren't sure if we were seeing all the info. We were a little confused by the heading 'SPOTLIGHT::RESOURCES::.." and the numbers appearing below it, perhaps something like 'Spotlight Harvester Status' and then the job being processed below that might make more sense? We were also confused by what the {} under details meant. Also there is no X to close the window.

The other thing that stands out is because it is showing the status of 10 records at a time that list is going to get very long for a lot of jobs. Most collections have somewhere between 2-4K items, but our largest one has over 10K items. I wonder if grouping them in chunks of 50 or 100 might be better?

Those are my initial thoughts, but I'm sure I'll think of some more things once I get to try it out in QA/staging.

**Comment by bkiahstroud** [comment]
Thanks for clarifying! The usability issues have been captured in [this ticket](https://github.com/harvard-lts/CURIOSity/issues/104) and will be addressed. 

Changing the grouping to every 50 or 100 records instead of every 10 should be pretty straightforward. I've created a ticket to track that [here](https://github.com/harvard-lts/CURIOSity/issues/113). 

Given all that, can this ticket be closed?

**Comment by VanessaVenti** [comment]
Yes, we can close this one.
