### ISSUE TITLE
[2] Update default fields

### ISSUE THREAD

**Issue by summer-cook** [harvard-lts/CURIOSity#136]
## Summary

Update default fields to match metadata template >>>

"[2.0 Metadata Template.xlsx](https://docs.google.com/spreadsheets/d/1ku4jp73zvvFLSJt0j80h53g3Z7SThn-3rcFOPLpesk8/edit#gid=0) contains our existing mapping fields in the order we display them along with their field type and which views they are displayed in. Can the default fields be updated to match these?"

## Testing Instructions 

1. Login as an admin 
2. Navigate to Exhibit Dashboard > Items > Add Items 
3. Click the "Upload item" tab 
4. Validate that each field in the Acceptance Criteria is listed in the form<sup>1</sup>

<sup>1</sup> NOTE: Labels may differ slightly. Fields not listed in the Acceptance Criteria will also be present on the form (e.g. `URN`)

## Acceptance Criteria 

- [x] Additional Digital Items
- [x] Creator / Contributor
- [x] Attribution
- [x] Date
- [x] Place of Origin
- [x] Publisher
- [x] Description
- [x] Edition
- [x] Extent
- [x] Language
- [x] Genre
- [x] Digital Format
- [x] Contents
- [x] Subjects
- [x] Culture
- [x] Style / Period
- [x] Materials / Techniques
- [x] Places
- [x] Notes
- [x] Cite As
- [x] In Collection
- [x] Container
- [x] Series
- [x] Classification
- [x] Repository
- [x] Rights
- [x] Record ID
- [x] Finding Aid Component
- [x] HOLLIS Record
- [x] Harvard Art Museums
- [x] Harvard Digital Collections
- [x] Available To
- [x] Collection
- [x] Finding Aid
- [x] URN
- [x] Exhibit Tags

**Comment by bkiahstroud** [comment]
Related conversation: https://github.com/harvard-lts/CURIOSity/issues/132#issuecomment-1211346790

**Comment by bkiahstroud** [comment]
Related MR (though not related to Vanessa's comment ^ above): https://gitlab.com/notch8/harvard-curiosity/-/merge_requests/167

**Comment by dl-maura** [comment]
@VanessaVenti is the issue here just the names or are you also seeing some of the things from your list not appearing?

**Comment by VanessaVenti** [comment]
@bkiahstroud - it looks like this update effects only newly created exhibits (made after this update was deployed), not existing ones (that were created before this deploy). This raises a couple of questions about what our process for making future updates should look like:

1. If we add or rename or delete a field in the default mapping that we want reflected in existing exhibits, should we manually make the updates in the UI to each of the existing exhibits?
2. If we add or rename or delete a field in the default mapping and DON'T make any change to an existing exhibit's fields in the UI, what happens if we reharvest items to that exhibit? (I'm not sure we have a case where we would do this intentionally, but just thinking through the variables)
3. Are there other considerations we should document for existing exhibits?

**Comment by bkiahstroud** [comment]
@VanessaVenti -- 

If you added a field and harvested, the field would be populated as expected. Likewise, if you deleted a field and harvested, the data would be removed. If you rename a field, you'll still need to update it manually in the UI (or a developer could write a script to update all the existing exhibit fields in bulk).

**Comment by VanessaVenti** [comment]
Thanks for the info @bkiahstroud!

@dl-maura I'm still testing this, but so far I noticed Description seems to be missing from the item detail view. It should be on the following records: 
https://curiosity-qa.lib.harvard.edu/vv-metadata-field-test-9-22-2022/catalog/19-990006049270203941_RADSCHL:1267673
https://curiosity-qa.lib.harvard.edu/vv-metadata-field-test-9-22-2022/catalog/19-ARN00007C00040
https://curiosity-qa.lib.harvard.edu/vv-metadata-field-test-9-22-2022/catalog/19-W160165_URN-3:HULARCH:53681

**Comment by dl-maura** [comment]
Order adjustments coming in an MR, have some questions to @VanessaVenti re: description and finding aids

**Comment by dl-maura** [comment]
This has been done on my local, VV has seen, putting in an MR to gitlab!

**Comment by VanessaVenti** [comment]
Looks good on QA!
