### ISSUE TITLE
Harvester questions

### ISSUE THREAD

**Issue by VanessaVenti** [harvard-lts/CURIOSity#214]
1. How do we delete a job? For example if we’ve already harvested **contagion** to an exhibit and we accidentally harvest **demo** to it, can we delete **demo** without wiping out **contagion** items as well?
2. If you harvest a second (different) set of items to an exhibit will it reindex everything it had harvested in the first set or just the second set of items?
3. Will the harvester send the success email before indexing is complete? (looks like yes)
4. Is there a way to tell when reindexing is complete if you are reharvesting a job?
5. Can job info be added to the harvester modal window? For example, it’d be helpful to know what oai-path, set spec, and yaml were used in harvesting with set spec being the most important. This would be helpful for both troubleshooting errors (like if we type the wrong thing by accident), but also to know the history of sets that are harvested to an exhibit.

**Comment by dl-maura** [comment]
Notes from meeting:
1. Our guess is the way this was happening is going into the DB and purging and then purging from solr. No way to do this from UI, this would be a scripting task.
2. Only index what you harvested as far as we know
3. Yes, it sends the email before indexing is complete. So, we may want to change the wording of the email because it implies indexing is done. The OAI job finishing is what 'finishes' and sends an email, not the indexing jobs.
4. Delayed job dashboard
5. Adding setName to the modal is really easy, but depending how much info we want to add will affect the lift (but probably a light lift?). Would need to bring the view file from spotlight and override it which could make future updates more difficult.

**Comment by VanessaVenti** [comment]
I made a separate ticket (https://github.com/harvard-lts/CURIOSity/issues/217) for a couple notification improvements we can make in the future based on the above discussion.
