### ISSUE TITLE
Full-text search only retrieves the first word

### ISSUE THREAD

**Issue by VanessaVenti** [harvard-lts/CURIOSity#298]
When conducting a full-text search, only the first word entered in the search box is carried over to FTS. For example if you search ["Frederick Douglass" in SAEF](https://curiosity.lib.harvard.edu/slavery-abolition-emancipation-and-freedom/catalog?exhibit_id=slavery-abolition-emancipation-and-freedom&fulltext=true&q=Frederick+Douglass&search_field=all_fields), and then click on the first result, you'll see it [only searches "Frederick" in FTS](https://fts.lib.harvard.edu/fts/search?query=Frederick).

**Comment by dl-maura** [comment]
So the search actually IS working, the issue is if you use more than one word in your search the 'x in x matches' link that gets generated is broken probably due to an encoding bug

<img width="1419" alt="Screen Shot 2023-02-02 at 4 20 30 PM" src="https://user-images.githubusercontent.com/61880785/216452128-d198f871-242b-4dc4-a0ab-48d7f9165419.png">

**Comment by dl-maura** [comment]
Coe is in QA for @VanessaVenti to review in the ui

**Comment by VanessaVenti** [comment]
Looks good on QA!
