### ISSUE TITLE
Review Library theme for refinement

### ISSUE THREAD

**Issue by VanessaVenti** [harvard-lts/CURIOSity#33]
See Front End Design Epic issues for related stories for refining the Library theme in a Spotlight context.

Included in this review should be confirming whether Library theme supports: 

### Unused and/or hidden features
- Admin menu (when signed in)
- Sign in link - move to footer and relabel as 'STAFF LOGIN'
- Multi-lingual support (Stanford example: https://exhibits.stanford.edu/paci. Not currently used at Harvard but needed for sites like CRB where as a workaround they have both English and Chinese translations on the same page)
- Exhibit tags (not currently used)
- Items tags (not currently used)
- End users bookmarking items and saving searches/history. Is this still an option? (not currently used)

### New features
- Breadcrumbs
- Browse groups

**Comment by summer-cook** [comment]
Hi @VanessaVenti 
I am working on this ticket now. It wasn't as simple as just pulling in the views from the old site, so I am needing to go through the old site and individually pull pieces over to make the new site match your old theme.

just want to confirm that you do want everything that is on the unused/hidden features to remain hidden in the new site?

**Comment by VanessaVenti** [comment]
Hi @summer-cook  - thanks for asking! Actually, we want to show everything listed above and make sure we can see it all with the new theme. There will be features we will continue not to use, but we do want make sure they are not hidden if we do decide to use them.

**Comment by summer-cook** [comment]
Okay that is very good to know before I got too far into hiding them! 

so to break it down a bit more:

- Admin menu (when signed in) & Sign in link - move to footer and relabel as 'STAFF LOGIN'
_I will make sure that all the navigation/functionality shows when signed in only_ 


- Multi-lingual support (Stanford example: https://exhibits.stanford.edu/paci. Not currently used at Harvard but needed for sites like CRB where as a workaround they have both English and Chinese translations on the same page)
_This actually does not exist in either the old theme or in new vanilla spotlight. We can possibly bring them in at a later time though_ 

- Exhibit tags (not currently used)
_If you would like these to not be hidden, Is the placement of these in the vanilla spotlight ok for you guys? (ignore everything else about how it looks for now, it is in progress haha). They would show between the masthead (top title/headings) and the exhibits on the homepage. If you would like them to not appear there for now, I can hide them with CSS instead of removing them from the partial completely so that way we could easily add them back later._
<img width="1350" alt="Screen Shot 2022-04-26 at 12 46 10 PM" src="https://user-images.githubusercontent.com/73361970/165360992-de2a6b78-f1a1-433a-a9d1-15aec570d348.png">

- Item tags
_What do you mean by these exactly?_

- End users bookmarking items and saving searches/history. Is this still an option? (not currently used)
_I believe this was on option in blacklight, but not in spotlight._

- Breadcrumbs & Browse groups 
_will make sure these are brought over as well_

**Comment by summer-cook** [comment]
@VanessaVenti 
Thank you for all the input above! I am about to put in an MR for the homepage, but ill take all of this into consideration when I get to additional pages that include your specifications.

one more question:
Currently on the old version of spotlight, the exhibit descriptions on the homepage are visible below each exhibit. The new version has a built-in javascript functionality that allows the description to slide up when the user hovers over it. Here is what it would look like (with example exhibits):
https://share.getcloudapp.com/X6uEGj2l

Personally I think this looks a little more streamlined than having the descriptions always show below each exhibit. Would you like me to keep it like this? If not, I can totally make it look the same as the old site. Just wanted to run it past you in case you thought it would be a potential improvement.

**Comment by VanessaVenti** [comment]
@summer-cook We definitely have some design issues with our current homepage that we'd like to address, see https://github.com/harvard-lts/CURIOSity/issues/23 for details. I agree that the javascript solution might be a better approach and looks like it aligns with what we were thinking for updating this page. We'll just want to make sure it is keyboard accessible. There are a lot of [nit-picky front end design issues](https://github.com/orgs/harvard-lts/projects/4/views/1?visibleFields=%5B%22Title%22%2C%22Assignees%22%2C%22Status%22%2C%22Labels%22%5D&filterQuery=label%3A%22front+end+design+epic%22) in our backlog that I'd love to look at you when the timing makes sense. The hope is the new approach will address a lot of them automatically, but I'm sure there will be lots to review.

**Comment by summer-cook** [comment]
@VanessaVenti sounds great. I will keep the description hover for now (as this is what comes with Vanilla spotlight anyways) and later down the road I'll be happy to pick up #23 to refine the design of that page even more. We can discuss that further when I pick up that ticket. ･ᴗ･

**Comment by enriquediaz** [comment]
@VanessaVenti can you confirm the work represented in this item is done?

**Comment by VanessaVenti** [comment]
Looks good for now. Testing multi-lingual support needs to be revisted, but we aren't currently utilizing this feature so I will add this to the backlog.
