### ISSUE TITLE
Set up monitoring for delayed_jobs

### ISSUE THREAD

**Issue by VanessaVenti** [harvard-lts/CURIOSity#49]
delayed_jobs regularly needs to be restarted (approx. once a month depending on usage). When this happens a CURIOSity admin contacts devOps to check:
ps –ef | grep delayed_job

Then to start the delayed job:
Under the app directory do bin/delayed_job start &

Investigate if this process can be improved.

**Comment by bkiahstroud** [comment]
A possible solution would be running delayed_job in its own docker container. A version of this has already been successfully implemented in (what is currently) [a feature PR](https://gitlab.com/notch8/harvard-curiosity/-/merge_requests/51/diffs#f224ccece1ea592180f5e087c466b1371e1d19d2)

**Comment by VanessaVenti** [comment]
@dl-maura and @phil-plencner-hl - I think this one requires a dev to test. I've always been able to harvest so it looks like it's working on my end, but I don't know what has been implemented on the back end.

**Comment by dl-maura** [comment]
So, we are running delayed_jobs in its own container, I don't know if that means we won't have this issue?

**Comment by bkiahstroud** [comment]
When running in its own container, I've never seen the delayed job process stop without the container also stopping (indeed, it's set up in a way that if the main process ends, the container stops). 

This does **not** mean that delayed job will never need to be restarted; rather, the container may need to be restarted instead of the steps listed in the description. Restarting the container will restart the delayed job process. 

All that being said, monitoring the `worker` container's health should be sufficient. Also, you can usually tell if delayed job isn't running by going to `/delayed_job/overview` as an admin -- if the number of jobs doesn't decrease over a couple minutes, usually that means the process crashed.

**Comment by dl-maura** [comment]
Will add the check info to the wiki, but this can be closed
