### ISSUE TITLE
Ability to upload exported Exhibits (excluding resources)

### ISSUE THREAD

**Issue by bkiahstroud** [harvard-lts/CURIOSity#87]
## Summary

We need to be able to upload exported exhibits.  

Two test files: 
Clean demo version: https://drive.google.com/file/d/1Im376vVfoh12hPsetGCcsxWImNyMNz_O/view?usp=sharing
Actual exhibit: https://drive.google.com/file/d/1dSeBza_TKPRZZigxloL7x8FiGD_Q2njx/view?usp=sharing

The two files above are now in a [folder of example exports of some of our largest exhibits](https://drive.google.com/drive/u/1/folders/1SlOpuzlmPMWl1Mh-dedMPJQclkv_yCEt).

## Acceptance Criteria 

As an admin, I can successfully:

- [ ]  Import all files in [this folder](https://drive.google.com/drive/u/1/folders/1SlOpuzlmPMWl1Mh-dedMPJQclkv_yCEt) 
- [ ] Import Exhibits that have nested ("child") featured pages 
  - https://gitlab.com/notch8/harvard-curiosity/-/merge_requests/94
- [ ] Import Exhibits with their original ID 
  - https://gitlab.com/notch8/harvard-curiosity/-/merge_requests/87

## Testing Instructions 

For each file in [this folder](https://drive.google.com/drive/u/1/folders/1SlOpuzlmPMWl1Mh-dedMPJQclkv_yCEt), do the following: 

1. Download the JSON file 
2. Add the Exhibit's original ID to the JSON<sup>1</sup>
3. Login as an admin
4. Create a new Exhibit
5. Navigate to Exhibit Dashboard > General > Import Data
6. Click "Browse" and select the JSON file 
7. Click "Import Data" 
8. Confirm that all expected Exhibit data was imported correctly, including but not limited to: 
  a. ID
  b. Metadata (e.g. feature pages) 
  c. Assets (e.g. images)
  d. ~Resources (e.g. harvesters)~ Will be handled by https://github.com/harvard-lts/CURIOSity/issues/116

<sup>1</sup> See dropdown for example 

<details><summary>Dropdown</summary>

```json
{
  "id": 999, # <-- added Exhibit's original ID
  "title": "CURIOSity Demo Site ",
  "subtitle": "",
  "description": "Demonstration website for members of Harvard Library using the CURIOSity service to showcase CURIOSity features.",
```

</details>

**Comment by summer-cook** [comment]
@VanessaVenti 

Hi! So i figured out this does work, but I am not able to upload those 2 files you provided potentially because they are formatted a different way. Were these exported from the old version of curiosity? it seems like the formatting of how these exports are saved has changed between versions which is what causes an error when trying to import an old exhibit to the new site. 

I tested this on staging by exporting one of the example exhibits, and then reimporting that JSON file to the other example exhibit.  you will now see on staging that there are 2 "Example Exhibits." you should be able to create an exhibit on staging, customize it how you would like, export, and then import. Let me know if you have more questions about this.

**Comment by VanessaVenti** [comment]
Hi @summer-cook - thanks for taking a look at this. The use case for this is actually to investigate whether this as a solution for migrating exhibits from our current instance over to the new instance. So yes, the examples I gave are from the old version. Do you think there is a way to update/map them so they conform to the new version?

**Comment by summer-cook** [comment]
@VanessaVenti - yes, we will be able to map them from the old version to stop that bug from happening. We are currently working on doing this. As an update, we now do not hit an error while importing the old version's exhibits, but items are not importing successfully. It might depend on getting harvesting working first since it seems like the "actual exhibit" JSON file you provided imports a harvester as one of its resources, meaning it would run if harvesting was working to bring in the items. Is this how it worked when you used this feature in the old version?

Also Just to confirm, does the the "clean" demo version have items that should be importing? or no?

**Comment by bkiahstroud** [comment]
> Just chiming in to confirm there are multiple places you can upload images. feature_image sounds like it may be specific to the masthead so it'd be good to check where other uploaded images go. For example, when editing a site there is both a masthead and thumbnail under appearance/edit. There is also a masthead and thumbnail upload option for Browse Categories. When editing any page, there is a thumbnail tab where you can upload an image there. The Uploaded Item Row widget is another common place images are uploaded (which can be added to any page). And finally you can upload an image to the site's Contacts. I'm probably forgetting some others, but that's most of them.

**Comment by bkiahstroud** [comment]
@VanessaVenti that's really good to know, thank you for letting us know. For visibility, I have a solution working locally and have created an MR for it [here](https://gitlab.com/notch8/harvard-curiosity/-/merge_requests/87)

**Comment by bkiahstroud** [comment]
Blocked for QA by https://github.com/harvard-lts/CURIOSity/issues/116

**Comment by dl-maura** [comment]
I think this has been replaced by #144 since we did the basics, closing this ticket
